# Generated by Django 5.2 on 2025-10-04 21:20

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0067_noticia_contador_visitas_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('comprobante', models.URLField(blank=True, null=True)),
                ('comprobante_local', models.ImageField(blank=True, null=True, upload_to='donaciones/')),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la donación (opcional)', max_digits=10, null=True)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje del donante (opcional)', null=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
