# Generated by Django 5.2 on 2025-11-16 20:11

import diarioback.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0071_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.CreateModel(
            name='MensajeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Máximo 500 caracteres', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('duracion_dias', models.IntegerField(choices=[(1, '1 día'), (5, '5 días'), (7, '7 días (1 semana)')], default=7, help_text='Duración del mensaje antes de ser eliminado')),
                ('activo', models.BooleanField(default=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='diarioback.trabajador')),
            ],
            options={
                'verbose_name': 'Mensaje Global',
                'verbose_name_plural': 'Mensajes Globales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaMensajeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(help_text='Máximo 300 caracteres', max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='diarioback.mensajeglobal')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_enviadas', to='diarioback.trabajador')),
            ],
            options={
                'verbose_name': 'Respuesta a Mensaje Global',
                'verbose_name_plural': 'Respuestas a Mensajes Globales',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['fecha_expiracion', 'activo'], name='diarioback__fecha_e_9f9a27_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeglobal',
            index=models.Index(fields=['-fecha_creacion'], name='diarioback__fecha_c_f564cc_idx'),
        ),
    ]
