# Generated by Django 5.2 on 2025-11-16 21:16

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0072_alter_noticia_categorias_mensajeglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
