# Generated by Django 5.2 on 2025-11-17 13:28

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0073_alter_noticia_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['autor', 'estado', '-fecha_publicacion'], name='idx_autor_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['autor', '-fecha_publicacion'], name='idx_autor_fecha'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='idx_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['nombre_noticia'], name='idx_nombre_noticia'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['slug'], name='idx_slug'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-fecha_publicacion'], name='idx_fecha_pub_desc'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-contador_visitas', 'estado'], name='idx_visitas_estado'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['-contador_visitas_total', 'estado'], name='idx_visitas_total_estado'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['ultima_actualizacion_contador'], name='idx_ultima_act_contador'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', 'autor', '-fecha_publicacion'], name='idx_estado_autor_fecha'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categorias'], name='idx_categorias'),
        ),
        migrations.AddConstraint(
            model_name='noticia',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug'),
        ),
    ]
