# Generated by Django 5.2 on 2025-11-23 21:53

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0074_alter_noticia_options_alter_noticia_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='idx_home_featured'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-contador_visitas'], name='idx_home_most_viewed'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categorias', 'estado', '-fecha_publicacion'], name='idx_home_categories'),
        ),
    ]
