# Generated by Django 5.2 on 2025-11-23 22:08

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0075_alter_noticia_categorias_noticia_idx_home_featured_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='noticia',
            name='idx_home_featured',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='idx_home_most_viewed',
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='idx_home_categories',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
    ]
