# Generated by Django 5.2 on 2025-11-24 20:48

import diarioback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioback', '0076_remove_noticia_idx_home_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.TextField(blank=True, null=True, validators=[diarioback.models.Noticia.validate_categorias]),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='idx_home_featured'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-contador_visitas'], name='idx_home_most_viewed'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categorias', 'estado', '-fecha_publicacion'], name='idx_home_categories'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['nombre_noticia'], name='idx_search_title'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['Palabras_clave'], name='idx_search_keywords'),
        ),
    ]
